Fix SSR uglifyJs bug
xkjyeah/vue-google-maps pull request #235
Opened 2017-10-21 12:42 UTC by Ivan-Feofanov

Fix for issue #217

2017-10-26 10:13 UTC, homerjam commented on README.md
> +import * as VueGoogleMaps from '~/node_modules/vue2-google-maps'
Does this still not work?
```
import * as VueGoogleMaps from 'vue2-google-maps'
```

2017-10-26 10:13 UTC, homerjam commented
Maybe you should remove `dist` changes from PR @Ivan-Feofanov ?

2017-10-27 08:55 UTC, Ivan-Feofanov commented on README.md
> +import * as VueGoogleMaps from '~/node_modules/vue2-google-maps'
Only this way will work

2017-10-27 08:57 UTC, Ivan-Feofanov commented
@homerjam the meaning of this PR is to rebuild `dist` folder

2019-07-09 18:02 UTC, diegoazh commented
@Ivan-Feofanov the this folder will be change when a new version is released.

2019-07-09 18:04 UTC, diegoazh requested changes
@Ivan-Feofanov please remove the changes on `dist/` folder and resolve the conflicts in order to be merged.

2019-10-07 22:40 UTC, diegoazh commented
I think that this PR should be closed for inactivity on Oct 27.

2019-10-12 20:17 UTC, diegoazh commented
PR closed because the source branch of this change does not longer exist. Added to the readme file the proposal information.

2019-10-12 20:17 UTC, closed without merging