babel-polyfill. Updated webpack and node-sass.
xkjyeah/vue-google-maps pull request #468
Opened 2018-08-15 14:07 UTC by Richard1984

Solved core-js error: #465 
Updated webpack and node-sass to solve security problems.

2018-08-16 18:31 UTC, Richard1984 commented
# Packages

## New

* **@babel**/polyfill
* consolidate
* eslint-plugin-import
* eslint-plugin-vue
* eslint-plugin-node
* mini-css-extract-plugin
* optimize-css-assets-webpack-plugin
* uglifyjs-webpack-plugin

## Updated

* **@babel**/cli
* **@babel**/core
* **@babel**/plugin-proposal-object-rest-spread
* **@babel**/preset-env
* **@babel**/runtime
* babel-eslint
* babel-loader
* babel-plugin-minify-dead-code-elimination
* babel-plugin-transform-inline-environment-variables
* cross-env
* css-loader
* eslint
* eslint-config-standard
* eslint-plugin-html
* eslint-plugin-promise
* eslint-plugin-standard
* file-loader
* gh-pages
* lab
* puppeteer
* raw-loader
* shx
* style-loader
* template-html-loader
* vue
* vue-loader
* vue-router
* vue-template-compiler
* webpack
* webpack-cli

## Removed

* babel-preset-es2015
* babel-preset-stage-2
* code
* jsdom
* less
* less-loader
* lodash
* lodash-es
* lodash-webpack-plugin
* node-sass
* sass-loader
* stylus-loader
* vue-hot-reload-api
* vue-html-loader

# Files

## New

|  File |  Description  |
| --- | --- |
|  config/webpack.production.config.js  |  Webpack configuration (Production) |
|  config/webpack.development.config.js  |  Webpack configuration (Development) |
|  config/webpack.test.config.js  |  Webpack configuration (Test) |

# Problems

* 58 security problems: solved
* Issue #465

# More

* File optimization on build:
	1. mini-css-extract-plugin
	2. optimize-css-assets-webpack-plugin
	3. uglifyjs-webpack-plugin

2018-09-23 15:31 UTC, Richard1984 commented
What about this? https://github.com/Richard1984/vue-gmaps
Using vue-cli 3. @xkjyeah

2018-10-22 13:54 UTC, xkjyeah commented
Do you think you can remove `dist/*` to keep the PR clean?

2018-10-22 17:48 UTC, Richard1984 commented
Do you mean the content of dist or the folder itself?

2018-10-24 14:41 UTC, xkjyeah commented
the changes you've introduced to `dist`. I'll update that when publishing a new version

2018-10-24 19:06 UTC, Richard1984 commented
Sorry, I don't understand. :( Are you referring  to this PR or the other one?

> What about this? https://github.com/Richard1984/vue-gmaps
> Using vue-cli 3. @xkjyeah 

Because the content of *dist* folder in this PR is the same of the original repo.

2019-02-23 17:07 UTC, adekoyejoakinhanmi commented
Is this ever gonna be merged? More so how can I avoid the error this solves before this is finally merged?

2019-04-11 02:35 UTC, diegoazh commented
Please resolve this conflicts:
README.md
dist/vue-google-maps.js
package-lock.json
package.json
If you resolve this the I think the PR can be merged.

2019-04-12 13:30 UTC, durduliu2009 commented
It seems that this PR won't be merged too soon

2019-07-09 17:26 UTC, diegoazh reviewed
This changes looks right for me, I do not have any comment about that. Any one have comments on this PR?

2019-07-09 17:40 UTC, diegoazh commented
@Richard1984 can you solve the last conflicts and remove the changes in `dist/` folther, that @xkjyeah request you, I will like to merge this PR on the branch master as soon as posible. Thank you.

2019-07-09 18:05 UTC, diegoazh requested changes
Resolve conflicts and remove changes on `dist/` folder in order to be merged.

2019-07-10 11:15 UTC, diegoazh approved these changes

2019-07-10 11:16 UTC, diegoazh commented
Thank you, @Richard1984.

2019-07-10 11:34 UTC, diegoazh requested changes
Please upgrade the version in `package.json` accordingly I think this is not a braking change but is a important change because that I think it should be 0.11.0, but if you have doubts leave it as it is 0.10.4 and @xkjyeah will upgrade in a new released.

2019-07-10 11:34 UTC, diegoazh commented on package.json
> +  "version": "0.10.2",
Why you change the version from 0.10.4 to 0.10.2?

2019-07-10 11:37 UTC, diegoazh commented on package.json
> +  "version": "0.10.2",
After fix this I will merge this PR @Richard1984.

2019-07-10 15:04 UTC, diegoazh commented
Excellent work!!! @Richard1984

2019-07-10 15:04 UTC, diegoazh approved these changes

2019-07-10 15:19 UTC, merged

2019-07-14 11:03 UTC, JoseGoncalves commented
Hi @diegoazh and @Richard1984, first of all thanks for keeping this library alive and updated.

Nevertheless, there is a change in this PR that I do not agree.
You have moved @babel/runtime to devDependencies. As the name of the package implies, is to be used in runtime, i.e., is to be set in dependencies and not in devDependencies. See [@babel/plugin-transform-runtime](https://babeljs.io/docs/en/babel-plugin-transform-runtime) documentation for extra info.

We can question if @babel/runtime package is at all needed, and it will not if you use vue2-google-maps in a webpack environment, but, if it's used directly in an old browser (e.g. IE), vue2-google-maps may stop work with this change.

So my point is, @babel/runtime should be removed if support for old browsers whithout a build environment like webpack is not desired or should be included in the vue2-google-maps dependencies otherwise.

2019-07-15 14:49 UTC, diegoazh commented
@JoseGoncalves you right. I missed this detail. Can you create a new PR with this changes?

2019-07-15 15:12 UTC, JoseGoncalves commented
@diegoazh Sure! But in each way should we go, i.e., should we remove @babel/runtime package or should we move it to dependencies?

2019-07-15 15:50 UTC, diegoazh commented
@JoseGoncalves is there a way to keep these two possibilities or they are mutually exclusive?

2019-07-15 16:40 UTC, JoseGoncalves commented
They are mutually exclusive.
Has you have @babel/runtime set right now (in devDependencies) is exactly the same has not having it at all (but should be removed for consistency).
If it was my call, I would opt for removing that package. I don't think that, in the current days, someone is building Vue apps without a build system like Webpack.
In that case you don't need @babel/runtime, even to run your app in old browsers, because the build system handles the poyfills and transpilation for you.

2019-07-15 17:24 UTC, diegoazh commented
@JoseGoncalves is correct, is very difficult to think someone developing a vuejs app without webpack, please remove it.