chore(docs): add custom marker documentation
xkjyeah/vue-google-maps pull request #51
Opened 2017-02-26 16:00 UTC by awitherow

add documentation about how to add custom markers, derived from discussion in https://github.com/xkjyeah/vue-google-maps/issues/38

2017-02-26 16:03 UTC, awitherow commented on README.md
> +    settings.defaultIconSettings = /* Do something with google.maps.Size */
@xkjyeah could you elaborate here what other things are available here via the google.maps object? or at least point to documentation somehow.

2017-02-28 12:02 UTC, awitherow commented on README.md
> +    settings.defaultIconSettings = /* Do something with google.maps.Size */
@xkjyeah 👍

2017-02-28 14:31 UTC, xkjyeah commented on README.md
> +    settings.defaultIconSettings = /* Do something with google.maps.Size */
er... to be honest the Google Maps API surprises me with every new version.

The link is https://developers.google.com/maps/documentation/javascript/3.exp/reference

2017-02-28 16:21 UTC, awitherow commented on README.md
> +    settings.defaultIconSettings = /* Do something with google.maps.Size */
@xkjyeah I can add a link to that so we everyone has an idea of what the options are.

2017-03-02 10:16 UTC, awitherow commented
@xkjyeah I've updated the documentation where you requested, adding simply a link for the user to go looking for what they can access themselves. Looks good?

2017-03-02 14:32 UTC, xkjyeah requested changes

2017-03-02 14:32 UTC, xkjyeah commented on README.md
> +```javascript
Either \`\`\`vue (if Github supports it) or \`\`\`html

2017-03-02 14:32 UTC, xkjyeah commented on README.md
> +    settings.defaultIconSettings = {};
I think it is worth showing how `google.maps` can be used here, e.g. for `google.maps.Size`.

2017-03-02 14:32 UTC, xkjyeah commented on README.md
> +To implement custom marker, best practice is to create a map settings file, which you can import into the page(s) where you use the gmap-map and gmap-marker tags. This is usually done in a project co
It is worth explaining the problem, that is, why:

```html
<gmap-marker :icon="{... size: new google.maps.Size(10,10)}"></gmap-marker>
```

does not work

2019-07-09 18:19 UTC, diegoazh commented
Please resolve the comments and conflicts in order to be merged @awitherow. Thank you.

2019-07-11 14:22 UTC, AllanOcelot commented
@diegoazh  - Last push was February 2018, I would vote to close this PR.
Given the two years, there's also a good chance this would need updating for changes in GM.

2019-07-11 16:04 UTC, diegoazh commented
@AllanOcelot you are right. I will test this with actual changes and if its not working I will close this PR.

2019-10-07 22:38 UTC, diegoazh commented
I think that this PR should be closed for inactivity.

2019-10-13 23:36 UTC, diegoazh commented
@AllanOcelot can you review this work and update it on a new PR? I think the author of this PR is no longer interested on this library.

2019-10-30 23:18 UTC, closed without merging